//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFFWindowsUpdate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WFFWindowsUpdate.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot required for installing updates..
        /// </summary>
        internal static string RebootRequiredForInstall {
            get {
                return ResourceManager.GetString("RebootRequiredForInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading &apos;{0}&apos; update..
        /// </summary>
        internal static string TraceMessageDownloadingUpdates {
            get {
                return ResourceManager.GetString("TraceMessageDownloadingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now running with process identity (&apos;{0}&apos;)..
        /// </summary>
        internal static string TraceMessageImpersonatingProcessIdentity {
            get {
                return ResourceManager.GetString("TraceMessageImpersonatingProcessIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now running as user &apos;{0}&apos;..
        /// </summary>
        internal static string TraceMessageImpersonatingUser {
            get {
                return ResourceManager.GetString("TraceMessageImpersonatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Code: &apos;{0}&apos;.
        /// </summary>
        internal static string TraceMessageInstallationResultCode {
            get {
                return ResourceManager.GetString("TraceMessageInstallationResultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing &apos;{0}&apos; update..
        /// </summary>
        internal static string TraceMessageInstallingUpdates {
            get {
                return ResourceManager.GetString("TraceMessageInstallingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; updates found..
        /// </summary>
        internal static string TraceMessageNumberOfUpdates {
            get {
                return ResourceManager.GetString("TraceMessageNumberOfUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot not required..
        /// </summary>
        internal static string TraceMessageRebootNotRequired {
            get {
                return ResourceManager.GetString("TraceMessageRebootNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot required..
        /// </summary>
        internal static string TraceMessageRebootRequired {
            get {
                return ResourceManager.GetString("TraceMessageRebootRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverting from running as &apos;{0}&apos;..
        /// </summary>
        internal static string TraceMessageRevertingFromImpersonation {
            get {
                return ResourceManager.GetString("TraceMessageRevertingFromImpersonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for updates..
        /// </summary>
        internal static string TraceMessageSearchingForUpdates {
            get {
                return ResourceManager.GetString("TraceMessageSearchingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs the windows updates..
        /// </summary>
        internal static string WindowsUpdateProviderDescription {
            get {
                return ResourceManager.GetString("WindowsUpdateProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SM Windows Update.
        /// </summary>
        internal static string WindowsUpdateProviderFriendlyName {
            get {
                return ResourceManager.GetString("WindowsUpdateProviderFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong AsyncResult passed in as argument..
        /// </summary>
        internal static string WrongAsyncResult {
            get {
                return ResourceManager.GetString("WrongAsyncResult", resourceCulture);
            }
        }
    }
}
